### ISSUE TITLE
Possible issue with ES6 syntax (SyntaxError: Unexpected token export)

### ISSUE THREAD

**Issue by rtyx** [ngx-utils/cookies#3]
Hi there. 

I'm finding some problems when I try to run my express server and I'm using the cookies module. 

This is the error:

```
[universal-sandbox] node dist/server.js
/Users/.../Documents/Playground/universal-sandbox/node_modules/@ngx-utils/cookies/src/browser/index.js:1
(function (exports, require, module, __filename, __dirname) { export * from './browser-cookies.module';
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/.../Documents/Playground/universal-sandbox/dist/server.js:1:20221)

```

```
And this is my config:

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.5.0
Node: 8.3.0
OS: darwin x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.7
typescript: 2.4.2
webpack-node-externals: 1.6.0
webpack: 3.8.1

```

I think it's a problem of ES6 syntax, but I am wondering if it has happened to more people and how did they solve it. Should I transpile the entire module with babel to commonjs target? Is there a way of configuring node so that it runs ES6 code?

Thanks!

**Comment by gigadie** [comment]
I had to add an extra step to my `package.json` file to have this to run.

Install the following:
`npm install --save-dev babel babel-cli babel-preset-es2015`

Then add this step in your package.json file to execute before building your project for server-side:

`"babel:ngx-utils": "node node_modules/babel-cli/bin/babel.js node_modules/@ngx-utils/cookies --out-dir node_modules/@ngx-utils/cookies --presets es2015"`

For example `"build:ssr": "npm run babel:ngx-utils && ...rest of commands here..."`

This will make it to work.

But `ngx-utils/cookies` should be compiled and put on `npm` already with `es5` as target in order to work on `nodejs express` server.
